extend-exclude = ["*pb2.py", "*pb2_grpc.py", "*pb2.pyi"]

[format]
quote-style = "double"
indent-style = "tab"
docstring-code-format = false
skip-magic-trailing-comma = true

[lint.flake8-annotations]
ignore-fully-untyped = false