name: gobuild

on:
  push:
    branches:
      - "*"
  
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Build go apps
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.0"

      - name: Prepare dependencies
        run: |
          cd go
          go mod download

      - name: Build access-manager-api app
        run: |
          cd go/access-manager/cmd/access-manager-api
          go build