name: golinters

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "go/**"

jobs:
  linters:
    name: Run Go linters
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"
      
      - name: Setup protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "29.x"

      - name: Download go dependencies
        run: |
          cd go
          go mod download

      - name: Download protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Add Go bin to PATH
        run: |
          echo "${{ runner.tool_cache }}/go/$(go version | awk '{ print $3 }')/*/bin" >> $GITHUB_PATH

      - name: Generate go gRPC files
        run: |
          protoc api/access-manager/v1/*.proto --go_out=$GO_PROTO_OUT --go-grpc_out=$GO_PROTO_OUT        

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: "v1.60"
          working-directory: "go"