name: gotest

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "go/**"

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go enviroment
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.0"

      - name: Run Go tests
        run: |
          cd go
          go test -race ./...