name: python-generate

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "python/**"

jobs:
  generate-grpc:
    name: Verify python gRPC generation
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Python setup
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.8'

      - name: Install grpc requirements
        run: pip install -r python/gen/grpc-requirements.txt

      - name: Generate python gRPC files
        run: bash python/gen/generate_grpc.sh
